version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      kubectl: 1.21

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Configuring kubectl for EKS Cluster: $EKS_CLUSTER_NAME"
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Downloading latest Prisma Cloud twistcli..."
      - curl -k -u "$PRISMA_USER:$PRISMA_PASS" "$PRISMA_CONSOLE_URL/api/v1/util/twistcli" --output twistcli
      - chmod +x ./twistcli
      - >
        ./twistcli app-embedded embed 
        --address $PRISMA_CONSOLE_URL 
        --user $PRISMA_USER 
        --password $PRISMA_PASS 
        --app-id my-secure-app
        Dockerfile
      - echo "Building the secured Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Pushing the image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Starting deployment to EKS Fargate..."
      - IMAGE_URL="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - sed -i "s|image:.*|image: $IMAGE_URL|g" k8s/deployment.yml
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f k8s/deployment.yml
      - kubectl apply -f k8s/service.yml
      - echo "Deployment complete! 🎉"
